language: ruby
rvm:
  - 2.7.1
branches:
  only:
  - master
before_script: 
  # - cp -rfv docs/_includes .
  - chmod +x ./_includes/scripts/cibuild
# path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./_includes/scripts/cibuild
deploy:
  provider: pages
  repo: median-lab/median-home
  email: wanglj7@mail.sustech.edu.cn
  name: median-lab
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  keep-history: true
  on:
    branch: master
    target_branch: gh-pages
